server {
    listen 8000;
    root /var/www/html/browser;
    index index.html;

    access_log off;
    error_log /var/log/nginx/error.log crit;

    location / {
        try_files $uri $uri/ /index.html;
    }
}